/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.beothorn;

public class App {

    public static void main(String[] args) throws InterruptedException {
        System.out.println("Hello World");
    }
}
