/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.beothorn;

public class App {

    public static void main(String[] args){
        App app = new App();
        if (args.length != 1) {
            System.err.println("Usage: java -jar fizzbuzz.jar [number]");
            System.exit(1);
        }
        try {
            int max = Integer.parseInt(args[0]);
            app.printFizzBuzzFor(max);
        } catch (NumberFormatException e){
            System.err.println("Use valid integers as parameter." +
                    "\nUsage: java -jar fizzbuzz.jar [number]");
            System.exit(1);
        }
    }

    void printFizzBuzzFor(final int max) {
        for (int i = 1; i <= max; i++) {
            System.out.println(getLineFor(i));
        }
    }

    private String getLineFor(final int i) {
        if (i % 3 != 0 && i % 5 != 0) return number(i);
        if (i % 3 == 0 && i % 5 == 0) return fizzBuzz();
        if (i % 3 == 0) return fizz();
        return buzz();
    }

    private String fizz() {
        return "Fizz";
    }

    private String buzz() {
        return "Buzz";
    }

    private String fizzBuzz() {
        return "Fizz Buzz";
    }

    private String number(final int number) {
        return Integer.toString(number);
    }
}
