/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.fizzbuzz;

public class App {

    public static void main(String[] args) throws InterruptedException {
        App app = new App();
        if (args.length == 0) {
            System.err.println("Usage: java -jar fizzbuzz.jar [number] <number for another thread>");
            System.exit(1);
        }
        final Thread[] allFizzBuzz = new Thread[args.length];
        try {
            for (int i = 0; i < args.length; i++) {
                final int max = Integer.parseInt(args[i]);
                allFizzBuzz[i] = new Thread(() -> {
                    System.out.println(max + " -> " + app.getFizzBuzzFor(max));
                });
                allFizzBuzz[i].setName("FizzBuzz "+i);
                allFizzBuzz[i].start();
            }
        } catch (NumberFormatException e){
            System.err.println("Use valid integers as parameter." +
                    "\nUsage: java -jar fizzbuzz.jar [number]");
            System.exit(1);
        }
        for (final Thread fizzBuzzThread : allFizzBuzz) {
            fizzBuzzThread.join();
        }
    }

    String getFizzBuzzFor(final int max) {
        StringBuilder sb = new StringBuilder();
        for (int i = 1; i <= max; i++) {
            sb.append("\"" + getLineFor(i) + "\" ");
        }
        return sb.toString();
    }

    public String getLineFor(final int i) {
        if (i % 3 != 0 && i % 5 != 0) return number(i);
        if (i % 3 == 0 && i % 5 == 0) return fizzBuzz();
        if (i % 3 == 0) return fizz();
        return buzz();
    }

    private String fizz() {
        return "Fizz";
    }

    private String buzz() {
        return "Buzz";
    }

    private String fizzBuzz() {
        return "Fizz Buzz";
    }

    private String number(final int number) {
        return Integer.toString(number);
    }
}
